# 2.6.0开始使用基于PathPatternParser的路径匹配，而Springfox版本一直没有更新还
# 是使用的AntPathMatcher导致了这个问题，要处理问题也很简单，修改yaml文件，
# 将SpringBoot路劲匹配模式修改为AntPathMatcher就可以了，
# 配置如下：spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# 配置swagger配置
knife4j:
  basic:
    username: admin
    password: 666666
    # 开启认证
    enable: true
  # 默认是false ,屏蔽所有Swagger的相关资源
  production: false
  # 是否开启swagger
  enable: true
  info:
    title: test
    description: "测试"
    version: "1.0.0"
    contact:
      name: "阳哥"
      url: "www.test.com"
      email: "xxx@qq.com"